config/routes.rb
Intro::Engine.routes.draw do
  namespace :admin do
    resources :sessions, only: [:new, :create] do
      delete :sign_out, on: :collection
    end

    resources :images, only: [:create]

    resources :tours do
      member do
        put :publish
      end

      collection do
        get  :route
        post :attempt
      end
    end

    root to: 'tours#index'
  end

  resources :tours, only: [:index] do
    post :record, on: :collection
  end
end

app/models/intro/tour.rb
module Intro
  class Tour < ActiveRecord::Base
    serialize :route, Hash
    serialize :options, Hash

    attr_accessible :ident, :controller_path, :action_name, :options, :route, :published, :expired_at if Rails::VERSION::MAJOR < 4

    has_many :tour_histories, class_name: 'Intro::TourHistory', dependent: :destroy

    validates :ident, presence: true, uniqueness: true

    scope :with_controller_and_action, ->(controller, action) { where(controller_path: controller, action_name: action) }
    scope :published, -> { where(published: true) }
    scope :recent, -> { order(created_at: :desc) }

    before_save :format_attributes
    before_save :update_route
    after_commit :clear_cache if Intro.config.cache

    def expose_attributes
      as_json(only: %i[id ident controller_path action_name options]).with_indifferent_access
    end

    def simple_route
      route[:simple] rescue nil
    end

    def simple_route_changed?
      return false unless route_changed?

      simple_route != route_was[:simple] rescue false
    end

    def strict_route?
      route[:strict] rescue false
    end

    def expired?
      !!expired_at && expired_at < Time.now
    end

    class << self
      def extract_route(url)
        url = "/#{url}" if url !~ /^((https?:\/\/)|(\/))/i
        uri = URI(url)

        {
          source: recognize_path(uri.path),
          query: uri.query
        }
      rescue
        {}
      end

      protected

      # Seek route info in main app and engines
      # @thanks https://gist.github.com/jtanium/6114632
      def recognize_path(path, options = {})
        Rails.application.routes.recognize_path(path, options)
      rescue ActionController::RoutingError
        Rails::Engine.subclasses.detect do |engine|
          engine_path   = engine.routes._generate_prefix({}) if engine.routes.respond_to?(:_generate_prefix)
          engine_path ||= engine.routes.find_script_name({}) if engine.routes.respond_to?(:find_script_name)
          next unless engine_path

          path_for_engine = path.gsub(%r(^#{engine_path}), '')
          recognized_path = engine.routes.recognize_path(path_for_engine, options) rescue nil
          break recognized_path if recognized_path
        end
      end
    end

    def format_attributes
      %i[ident controller_path action_name].each do |attribute|
        strip_attribute = send(attribute).try(:strip)
        send("#{attribute}=", strip_attribute)
      end

      self.options = JSON.parse(options) rescue {} unless options.is_a?(Hash)
      self.route   = JSON.parse(route) rescue {} unless route.is_a?(Hash)
    end

    def update_route
      if simple_route.present? && simple_route_changed?
        route = self.class.extract_route(simple_route)
        source = route[:source] || {}

        self.controller_path = source[:controller].to_s if self.controller_path.blank?
        self.action_name = source[:action].to_s if self.action_name.blank?
        self.route.reverse_merge!(route)
      end

      self.route[:strict] = %w[1 true].include?(self.route[:strict].to_s)
      self.route
    end

    def clear_cache
      if destroyed? || (previous_changes.keys & %w[controller_path action_name published]).any?
        Intro.cache.delete(controller_path, action_name)
      end
    end
  end
end

app/controllers/intro/admin/tours_controller.rb
module Intro
  module Admin
    class ToursController < ::Intro::Admin::ApplicationController
      if Rails::VERSION::MAJOR > 3
        before_action :authenticate
        before_action :require_tour, except: [:index, :new, :create, :route, :attempt]
      else
        before_filter :authenticate
        before_filter :require_tour, except: [:index, :new, :create, :route, :attempt]
      end

      def index
        @tours = Intro::Tour.page(params[:page]).per(15)
        @tours = @tours.recent
      end

      def new
        @tour = Intro::Tour.new
      end

      def create
        @tour = Intro::Tour.new(tour_params)

        if @tour.save
          redirect_to admin_tour_path(@tour), notice: t('intro.admin.add_success')
        else
          render :new
        end
      end

      def route
        render json: { data: Intro::Tour.extract_route(params[:path]) }
      end

      def attempt
        tour = Intro::Tour.new(tour_params)
        render json: { data: tour.expose_attributes }
      end

      def show
        render :edit
      end

      def edit; end

      def update
        flash.now[:notice] = t('intro.admin.update_success') if @tour.update_attributes(tour_params)
        render :edit
      end

      def destroy
        @tour.destroy
        redirect_to admin_tours_path
      end

      def publish
        @tour.update_attributes(published: 'true' == params[:published])
        redirect_to :back
      rescue => e
        redirect_to admin_tours_path
      end

      protected

      def tour_params
        _params = params[:tour].slice(:ident, :controller_path, :action_name, :options, :route, :expired_at)
        _params.permit! if Rails::VERSION::MAJOR > 3
        _params
      rescue
        {}
      end

      def require_tour
        @tour = Intro::Tour.find_by_id(params[:tour_id].presence || params[:id])

        @tour || respond_to do |format|
          format.html { redirect_to admin_tours_path }
          format.any  { head :not_found  }
        end
      end
    end
  end
end

app/controllers/intro/tours_controller.rb
require 'uri'

module Intro
  class ToursController < ::Intro::ApplicationController
    if Rails::VERSION::MAJOR > 3
      before_action :authenticate, only: :record
      before_action :require_tour, only: :record
    else
      before_filter :authenticate, only: :record
      before_filter :require_tour, only: :record
    end

    def index
      return render_unauthorized unless Intro.config.visible_without_signing_in || current_user

      tours = Intro::Tour.with_controller_and_action(params[:controller_path], params[:action_name])
      tours = tours.published

      Intro.cache.write(params[:controller_path], params[:action_name], tours.any?) if Intro.config.cache

      tours = filter_tours_by_route(tours)
      tours = filter_tours_by_histories(tours)
      tours = filter_tours_by_expired_time(tours)
      tours = filter_tours_by_signed_in(tours)

      render json: { data: tours.map(&:expose_attributes) }
    end

    def record
      history = Intro::TourHistory.with_user_and_tour(current_user, @tour).first_or_initialize
      history.increment!(:touch_count)
      render json: { message: t('intro.admin.update_success') }
    end

    protected

    def render_unauthorized
      render json: { message: t('intro.errors.unauthorized') }, status: :unauthorized
    end

    def authenticate
      render_unauthorized unless current_user
    end

    def require_tour
      @tour = Intro::Tour.find_by_id(params[:id]) if params[:id].present?
      render json: { message: t('intro.errors.tour_not_found') }, status: :not_found unless @tour
    end

    def filter_tours_by_route(tours)
      uri = URI(params[:original_url]) rescue nil if params[:original_url].present?
      return tours if uri.blank?

      # filter tours by simple route in strict
      strict_selector = lambda do |tour|
        simple = URI(tour.simple_route) rescue nil if tour.simple_route.present?
        return false if simple.blank?

        (simple.host.blank? || simple.host == uri.host) && simple.path == uri.path && simple.query == uri.query
      end

      # filter tours by path paramss
      path_route = Intro::Tour.extract_route(uri.to_s)
      path_selector = lambda do |tour|
        return true if path_route.blank?

        path_route[:source][:action] == tour.action_name &&
        path_route[:source][:controller] == tour.controller_path &&
        (tour.route[:source].blank? || path_route[:source].except(:controller, :action).keys.map(&:to_s) == tour.route[:source].except(:controller, :action).keys.map(&:to_s))
      end

      # filter tours by query string
      request_query = Rack::Utils.parse_nested_query(uri.query)
      query_selector = lambda do |tour|
        return true if tour.route[:query].blank?

        tour_query = Rack::Utils.parse_nested_query(tour.route[:query])
        (request_query.to_a & tour_query.to_a).any?
      end

      tours.select do |tour|
        if tour.strict_route?
          strict_selector.call(tour)
        else
          path_selector.call(tour) && query_selector.call(tour)
        end
      end
    end

    def filter_tours_by_histories(tours)
      tour_ids = Intro::TourHistory.with_user_and_tour(current_user, tours.map(&:id)).ge_max_touch.pluck(:tour_id)
      tours.select {|tour| tour_ids.exclude?(tour.id)}
    end

    def filter_tours_by_expired_time(tours)
      tours.reject(&:expired?)
    end

    def filter_tours_by_signed_in(tours)
      if Intro.config.visible_without_signing_in && !current_user
        tours.select {|tour| tour.options['not_sign_visible'] rescue false}
      else
        tours
      end
    end
  end
end

app/views/intro/admin/tours/_container.html.erb
<% content_for :body_class, 'intro-admin_tours' %>
<% content_for :head_content, intro_tags(enable: true) %>

<div class="intro-admin__container">
  <div class="intro-admin__box <%= yield(:box_class) %>">
    <div class="intro-admin__box-header">
      <div class="intro-admin__box-title">
        <%= yield(:box_title) %>
      </div>

      <div class="intro-admin__box-actions">
        <%= yield(:box_actions) %>

        <%= link_to t('intro.admin.sign_out'), sign_out_admin_intro_path, method: :delete %>
      </div>
    </div>

    <div class="intro-admin__box-content">
      <%= yield %>
    </div>
  </div>
</div>

app/views/intro/admin/tours/_form.html.erb
<%= form_for @tour, url: url, html: { class: "intro-admin__form intro-admin__tour-form #{yield(:tour_form_class)}" } do |f| %>
  <% if @tour.errors.any? %>
    <div class='field error'>
      <div class='message list'>
        <% @tour.errors.full_messages.each do |message| %>
          <%= content_tag :div, message, class: 'item' %>
        <% end %>
      </div>
    </div>
  <% elsif flash.notice %>
    <div class='field info'>
      <%= content_tag :div, flash.notice, class: 'message' %>
    </div>
  <% end %>

  <div class='fields simple-route-fields'>
    <div class='twelve wide field'>
      <%= f.label :ident do %>
        <%= t('intro.admin.tour.simple_route') %>
        <i class='intro-admin__question' title="<%= t('intro.admin.tips.simple_route') %>"></i>
      <% end %>
      <%= text_field_tag 'tour[route][simple]', @tour.simple_route, placeholder: t('intro.admin.placeholders.simple_route'), class: 'js-tour-simple-route-input' %>
    </div>

    <div class='four wide field'>
      <div class='checkbox intro-admin__checkbox'>
        <%= check_box_tag 'tour[route][strict]', 1, @tour.strict_route? %>
        <%= label_tag 'tour[route][strict]', t('intro.admin.placeholders.strict_route'), title: t('intro.admin.tips.strict_route') %>
      </div>
    </div>
  </div>

  <div class='four fields'>
    <div class='field required'>
      <%= f.label :ident, t('intro.admin.tour.ident') %>
      <%= f.text_field :ident, placeholder: t('intro.admin.placeholders.tour_ident'), required: true, class: 'js-tour-ident-input' %>
    </div>

    <div class='field'>
      <%= f.label :controller_path, 'Controller' %>
      <%= f.text_field :controller_path, placeholder: 'Controller path', class: 'js-tour-controller-input' %>
    </div>

    <div class='field'>
      <%= f.label :action_name, 'Action' %>
      <%= f.text_field :action_name, placeholder: 'Action name', class: 'js-tour-action-input' %>
    </div>

    <div class='field'>
      <%= f.label :action_name, t('intro.admin.tour.query_params') %>
      <%= text_field_tag 'tour[route][query]', @tour.route[:query], placeholder: t('intro.admin.placeholders.query_params'), class: 'js-tour-query-input' %>
    </div>
  </div>

  <%= render 'steps' %>

  <details class='field'>
    <summary><%= t('intro.admin.others') %></summary>
    <div class='intro-admin__tour-others'>
      <% if Intro.config.visible_without_signing_in %>
        <div class='field'>
          <div class='checkbox intro-admin__checkbox'>
            <%= check_box_tag 'tour[options][not_sign_visible]', 1, @tour.options['not_sign_visible'] %>
            <%= label_tag 'tour[options][not_sign_visible]', t('intro.admin.placeholders.not_sign_visible') %>
          </div>
        </div>
      <% end %>

      <div class='field'>
        <div class='checkbox intro-admin__checkbox'>
          <%= check_box_tag 'tour[options][overlay_visible]', 1, @tour.options['overlay_visible'] %>
          <%= label_tag 'tour[options][overlay_visible]', t('intro.admin.placeholders.overlay_visible') %>
        </div>
      </div>

      <% btn_visible = @tour.new_record? || @tour.options['btn_visible'] %>

      <div class='field' style="<%= 'margin-bottom: 1em;' unless btn_visible %>">
        <div class='checkbox intro-admin__checkbox'>
          <%= check_box_tag 'tour[options][btn_visible]', 1, btn_visible, class: 'js-intro-btn-visible-input' %>
          <%= label_tag 'tour[options][btn_visible]', t('intro.admin.placeholders.btn_visible') %>
        </div>
      </div>

      <div class='two fields js-intro-complete-btn-fields <%= 'intro-admin__hide' unless btn_visible %>'>
        <%= render 'local_field',
          label: { name: :btn_complete_text, content: t('intro.admin.tour.btn_complete_text') },
          input: { name: 'tour[options][btn_complete_text]', object: @tour.options, attr: :btn_complete_text, options: { placeholder: t('intro.admin.placeholders.btn_complete_text') } }
        %>

        <div class='field'>
          <%= label_tag :btn_complete_link, t('intro.admin.tour.btn_complete_link') %>
          <%= text_field_tag 'tour[options][btn_complete_link]', @tour.options['btn_complete_link'], placeholder: t('intro.admin.placeholders.btn_complete_link') %>
        </div>
      </div>

      <div class='three fields'>
        <div class='field'>
          <%= f.label :expired_at, t('intro.admin.tour.expired_time') %>
          <%= f.text_field :expired_at, type: :date %>
        </div>
      </div>
    </div>
  </details>

  <div class='field intro-admin__tour-actions'>
    <%= button_tag t('intro.admin.submit'), class: 'intro-admin__button prime', type: :submit %>
    <%= button_tag t('intro.admin.test'), class: 'intro-admin__button js-intro-admin__button-test', type: :button %>
    <%= yield(:form_actions) %>
  </div>
<% end %>

<script>
  $(function () {
    var introTour

    // auto fill ident, controller, action, query input
    $('.js-tour-simple-route-input').change(function (e) {
      if (!e.target.value) return

      var $identInput = $('.js-tour-ident-input')
      var $controllerInput = $('.js-tour-controller-input')
      var $actionInput = $('.js-tour-action-input')
      var $queryInput = $('.js-tour-query-input')

      $.ajax({
        method: 'GET',
        url: "<%= route_admin_tours_path %>?path=" + encodeURIComponent(e.target.value),
        contentType: 'application/json',
        success: function (res) {
          var data = res && res.data
          if (!data) return

          if (data.source) {
            $controllerInput.val(data.source.controller)
            $actionInput.val(data.source.action)

            if (/^(([\/\w]+)#(\w+)-.*)|(\s*)$/.test($identInput.val())) {
              $identInput.val(data.source.controller + '#' + data.source.action + '-' + Math.random().toString(36).slice(-6))
            }
          }

          if (data.query) {
            $queryInput.val(data.query)
          }
        }
      })
    })

    // test tour
    $('.js-intro-admin__button-test').click(function () {
      var $this = $(this)
      var $form = $('.intro-admin__tour-form')

      if ($this.hasClass('intro-loading')) return

      $.ajax({
        method: 'POST',
        url: "<%= attempt_admin_tours_path %>",
        data: $form.serialize().replace(/&_method=(put|patch)&/i, '&_method=post&'),
        beforeSend: function () {
          $this.addClass('intro-loading')
          introTour && introTour.hide()
        },
        success: function (res) {
          if (res.data) {
            introTour = new window._intro.Tour(res.data)

            introTour.test({
              element: '.js-intro-admin__button-test'
            })
          }

          $this.removeClass('intro-loading')
        },
        error: function () {
          $this.removeClass('intro-loading')
        }
      })

    })

    // complete btn actions
    $('.js-intro-btn-visible-input').change(function (e) {
      var $field = $(this).closest('.field')
      var $completeBtnFields = $('.js-intro-complete-btn-fields')

      if (e.target.checked) {
        $completeBtnFields.removeClass('intro-admin__hide')
        $field.css('marginBottom', 'null')
      } else {
        $completeBtnFields.addClass('intro-admin__hide')
        $field.css('marginBottom', '1em')
      }
    })

    // local field
    $('.intro-admin__tour-form').on('change', '.js-intro-admin__locale-select', function () {
      var $this = $(this)
      var $field = $this.closest('.field')

      $field.find('.locale-input').removeClass('active')
      $field.find('.locale-input[data-locale="' + $this.val() + '"]').addClass('active')
    })
  })
</script>

app/views/intro/admin/tours/_local_field.html.erb
<% text_tag_method = :textarea == input[:type] ? :text_area_tag : :text_field_tag %>
<% render_locale_input = ->(locale, options) do
    send(text_tag_method,
      input[:name].to_s.gsub(/\[(\w+)\]$/, "[\\1_#{locale}]"),
      (input[:object]["#{input[:attr]}_#{locale}"].presence || input[:object][input[:attr].to_s] rescue ''),
      options)
  end
%>

<div class='field local-field'>
  <div class='header'>
    <%= label_tag label[:name], label[:content] %>
    <div class='intro-admin__select'>
      <%= select_tag '_', options_for_select(I18n.available_locales, I18n.locale), class: 'js-intro-admin__locale-select' %>
    </div>
  </div>
  <div class='input-group'>
    <% I18n.available_locales.each do |locale| %>
      <% input_class = "locale-input #{input[:options][:class] rescue ''} #{'active' if locale == I18n.locale}"  %>
      <%= render_locale_input.call(locale, input[:options].merge(class: input_class, 'data-locale' => locale)) %>
    <% end %>
  </div>
</div>

app/views/intro/admin/tours/_steps.html.erb
<div class='intro-admin__steps'>
  <h4 class='header'><%= t('intro.admin.component.name') %></h4>

  <div class='content'>
    <% (@tour.options['steps'] || [{}]).each_with_index do |step, index| %>
      <%= render 'step', step: step, index: index %>
    <% end %>
  </div>

  <%= button_tag class: 'intro-admin__button large add-step-button', type: :button do %>
    &plus;
  <% end %>
</div>

<script>
  $(function () {
    var $steps = $('.intro-admin__steps')

    function refreshStepIndexes () {
      $('.intro-admin__step').each(function (index, step) {
        var $step = $(step)

        $step.find('.js-intro-step-index').text(index + 1)
        $step.find('.checkbox').each(function (_, checkbox) {
          var $checkbox = $(checkbox)
          var scope = $checkbox.data('scope')

          $checkbox.find('> input').attr('id', 'intro-admin__step-' + scope + '-' + index)
          $checkbox.find('> label').attr('for', 'intro-admin__step-' + scope + '-' + index)
        })
      })
    }

    // remove step
    $steps.on('click', '.intro-admin__step-remove', function () {
      var $this = $(this)
      $this.closest('.intro-admin__step').remove()

      refreshStepIndexes()
    })

    // add step
    $steps.on('click', '.add-step-button', function () {
      $steps.find('.content').append("<%= escape_javascript render('step', index: 1) %>")

      refreshStepIndexes()
    })

    // upload image
    function uploadImage (uploadBtn, file) {
      var $uploadBtn = $(uploadBtn)
      var $step = $uploadBtn.closest('.intro-admin__step')
      var $imageUrlInput = $step.find('.js-intro-admin__image-url')
      var formData

      if (!file) {
        $imageUrlInput.val('')
        $imageUrlInput.trigger('change')
        return
      }

      if ($uploadBtn.hasClass('intro-loading')) return

      formData = new FormData()
      formData.append('image', file)

      $.ajax({
        method: 'POST',
        url: "<%= admin_images_path %>",
        data: formData,
        contentType: false,
        processData: false,
        cache: false,
        beforeSend: function () {
          $uploadBtn.addClass('intro-loading')
        },
        success: function (res) {
          if (res.data && res.data.url) {
            $imageUrlInput.val(res.data.url)
          } else {
            $imageUrlInput.val('')
          }
          $imageUrlInput.trigger('change')
          $uploadBtn.removeClass('intro-loading')
        },
        error: function () {
          $uploadBtn.removeClass('intro-loading')
        }
      })
    }

    $steps.on('click', '.js-intro-admin__button-upload', function () {
      var $this = $(this)
      var $imageInput = $this.data('imageInput')

      if (!$imageInput) {
        $imageInput = $('<input type="file" accept="image/jpg, image/jpeg, image/png, image/gif, image/webp">')
        $imageInput.change(function () {
          uploadImage($this, this.files[0])
        })
        $this.data('imageInput', $imageInput)
      }

      $imageInput.trigger('click')
    })

    $steps.on('change', '.js-intro-admin__image-url', function () {
      var $this = $(this)
      var $step = $this.closest('.intro-admin__step')
      var $widthInput = $step.find('.js-intro-admin__image-width')
      var $heightInput = $step.find('.js-intro-admin__image-height')

      if ($this.val()) {
        $('<img />').attr('src', $this.val()).load(function () {
          $widthInput.val(this.width)
          $heightInput.val(this.height)
        })
      } else {
        $widthInput.val('')
        $heightInput.val('')
      }
    })
  })
</script>

app/views/intro/admin/tours/edit.html.erb
<% content_for :doc_title, t('intro.admin.edit_tour') %>
<% content_for :box_class, 'intro-admin__box-tour' %>
<% content_for :box_title do %>
  <%= link_to admin_tours_path, class: 'intro-admin__box-title-arrow' do %>
    &#8249;
  <% end %>
  <%= t('intro.admin.edit_tour') %>
<% end %>
<% content_for :box_actions do %>
  <%= link_to t('intro.admin.delete_tour'), admin_tour_path(@tour), method: :delete, data: { confirm: t('intro.admin.tips.delete_tour_confirm') } %>
<% end %>
<% content_for :form_actions do %>
  <%= link_to (@tour.published? ? t('intro.admin.unpublish') : t('intro.admin.publish')), publish_admin_tour_path(@tour, published: !@tour.published), method: :put, class: 'intro-admin__button' %>
<% end %>

<%= render layout: 'intro/admin/tours/container' do %>
  <%= render 'intro/admin/tours/form', url: admin_tour_path(@tour) %>
<% end %>

app/views/intro/admin/tours/index.html.erb
<% content_for :doc_title, t('intro.admin.tour_list') %>
<% content_for :box_class, 'intro-admin__box-tours' %>
<% content_for :box_title, t('intro.admin.tour_list') %>
<% content_for :box_actions do %>
  <%= link_to t('intro.admin.add_tour'), new_admin_tour_path %>
<% end%>

<%= render layout: 'intro/admin/tours/container' do %>
  <% if @tours.blank? %>
    <div class='message'>
      <%= t('intro.admin.none_tours') %>
    </div>
  <% else %>
    <table class='intro-admin__tours-table'>
      <thead>
        <tr>
          <th>ID</th>
          <th><%= t('intro.admin.tour.ident') %></th>
          <th><%= t('intro.admin.tour.simple_route') %></th>
          <th><%= t('intro.admin.tour.created_time') %></th>
          <th><%= t('intro.admin.tour.expired_time') %></th>
          <th><%= t('intro.admin.actions') %></th>
        </tr>
      </thead>
      <tbody>
        <% @tours.each do |tour| %>
          <tr class="intro-admin__tours-item <%= 'expired' if tour.expired? %>">
            <td><%= tour.id %></td>
            <td class='ident-column' title="<%= tour.ident %>"><%= tour.ident %></td>
            <td class='simple-route-column' title="<%= tour.simple_route %>"><%= tour.simple_route %></td>
            <td><%= tour.created_at.strftime('%F') %></td>
            <td><%= tour.expired_at.try(:strftime, '%F') %></td>
            <td>
              <%= link_to t('intro.admin.edit'), edit_admin_tour_path(tour) %>
              <%= link_to (tour.published? ? t('intro.admin.unpublish') : t('intro.admin.publish')), publish_admin_tour_path(tour, published: !tour.published), method: :put %>
              <%= link_to t('intro.admin.delete'), admin_tour_path(tour), method: :delete, data: { confirm: t('intro.admin.tips.delete_tour_confirm') } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <center class='intro-admin__pagination'>
      <%= paginate @tours %>
    </center>
  <% end %>
<% end %>

app/views/intro/admin/tours/new.html.erb
<% content_for :doc_title, t('intro.admin.add_tour') %>
<% content_for :box_class, 'intro-admin__box-tour' %>
<% content_for :box_title do %>
  <%= link_to admin_tours_path, class: 'intro-admin__box-title-arrow' do %>
    &#8249;
  <% end %>
  <%= t('intro.admin.add_tour') %>
<% end %>

<%= render layout: 'intro/admin/tours/container' do %>
  <%= render 'intro/admin/tours/form', url: admin_tours_path %>
<% end %>